#!/bin/bash

# See skript kasutab üksteise sisse ehitatud loope, et kuvada ekraanil viie rea kaupa viis tärni.

for (( i = 1; i <= 5; i++ )); do
	echo -n "$i. "
	for (( j = 1; j <= 5; j++ )); do
		echo -n "*"
	done
	echo ""
done
