#!/bin/bash

# See skript küsib kasutajalt täisarvu vahemikus 1-12 ja väljastab arvule vastava kuu

# Küsime kasutajalt kuu numbri. Kui kasutaja sisestab arvu väljaspool vahemikku 1-12
# või sisestab mitte täisarvu, antakse veateade ja runnitakse skript uuesti.
while true; do
	echo -n "Sisesta kuu number 1-12: "
	read kuu

	if [[ "$kuu" =~ ^[0-9]+$ ]] && (( kuu >= 1 && kuu <= 12 )); then
		break
	else
	        echo "Viga: Sisestatud väärtus pole täisarv või ei jää vahemikku 1-12."
	fi
done

case $kuu in
	"1") echo "$kuu. kuu on jaanuar.";;
	"2") echo "$kuu. kuu on veebruar.";;
	"3") echo "$kuu. kuu on märts.";;
	"4") echo "$kuu. kuu on aprill.";;
	"5") echo "$kuu. kuu on mai.";;
	"6") echo "$kuu. kuu on juuni.";;
	"7") echo "$kuu. kuu on juuli.";;
	"8") echo "$kuu. kuu on august.";;
	"9") echo "$kuu. kuu on september.";;
	"10") echo "$kuu. kuu on oktoober.";;
	"11") echo "$kuu. kuu on november.";;
	"12") echo "$kuu. kuu on detsember.";;
esac
