#!/bin/bash

# Kontrollib iga arvu 0 kuni 20, kas see on algarv või mitte.

for taisarv in {0..20}; do
    if (( taisarv < 2 )); then
        echo "$taisarv pole algarv."
    else
        algarv=true
        for ((jagaja=2; jagaja<=taisarv/2; jagaja++)); do
            if (( taisarv % jagaja == 0 )); then
                algarv=false
                break
            fi
        done

        if $algarv; then
            echo "$taisarv on algarv."
        else
            echo "$taisarv pole algarv."
        fi
    fi
done
