#!/bin/bash

# See skript arvutab, mitu on täielikult täidetud bussi ja mitu inimest jääb maha

echo -n "Sisesta reisijate arv: "
read reisijad
echo -n "Sisesta kohtade arv ühes bussis: "
read kohad

busse=$((reisijad / kohad))
mahajaajad=$((reisijad % kohad))
echo "Täis busse on ${busse}. Mahajääjaid on ${mahajaajad}."
