#!/bin/bash

# See skript arvutab, mitu on täielikult täidetud bussi ja mitu inimest jääb maha

echo -n "Sisesta reisijate arv: "
read reisijad
if ! [[ "$reisijad" =~ ^[0-9]+$ ]]; then
    echo "Viga: palun sisesta täisarv."
    exit 1
fi

echo -n "Sisesta kohtade arv ühes bussis: "
read kohad
if ! [[ "$kohad" =~ ^[0-9]+$ ]]; then
    echo "Viga: palun sisesta täisarv."
    exit 1
fi

busse=$((reisijad / kohad))
mahajaajad=$((reisijad % kohad))
echo "Täis busse on ${busse}. Mahajääjaid on ${mahajaajad}."
