#!/bin/bash

# See skript väljastab, kes valiti Eesti presidendiks aastal 2016
aasta=2016
president="Kersti Kaljulaid"
lause_keskosa=". aastal valiti Eesti presidendiks "
lause="${aasta}$lause_keskosa$president."
echo $lause
