#!/bin/bash

# See skript arvutab, mitu on täielikult täidetud bussi ja mitu inimest jääb maha

while true; do
	echo -n "Sisesta reisijate arv: "
	read reisijad
	if [[ "$reisijad" =~ ^[0-9]+$ ]]; then
		echo "Reisijaid on $reisijad."
		break
	else
		echo "Viga: Sisestatud väärtus pole täisarv."
	fi
done

while true; do
	echo -n "Sisesta kohtade arv ühes bussis: "
	read kohad
        if [[ "$kohad" =~ ^[0-9]+$ ]]; then
                echo "Kohti on $kohad."
                break
        else
                echo "Viga: Sisestatud väärtus pole täisarv."
        fi
done

busse=$((reisijad / kohad))
mahajaajad=$((reisijad % kohad))
echo "Täis busse on ${busse}. Üle jääb ${mahajaajad} inimest."

if ((mahajaajad > 0)); then
	busse=$((busse + 1))
fi

echo "Kokku on vaja $busse bussi."
