#!/bin/bash

# Argumendi kontroll
if [ -z "$1" ]; then
	echo "Viga! Skripti kasutamiseks sisesta argument kujul ./paarsus <number>"
	exit 1
fi

if ! [[ "$1" =~ ^-?[0-9]+$ ]]; then
    echo "Viga: '$1' ei ole täisarv!"
    exit 1
fi

# Paarsuse kontroll
arv=$1
if (($arv % 2 == 0)); then
	echo "Antud arv on paaris."
else
	echo "Antud arv on paaritu."
fi
