#!/bin/bash
#
osch=0
echo "1. Unix (Sun Os)"
echo "2. Linux (Red Hat)"

while true; do
	echo -n "Select your os choice [1 or 2]? "
	read osch
	if [[ "$osch" =~ ^[0-9]+$ ]]; then
		if [ $osch -eq 1 ] ; then
		     echo "You Pick up Unix (Sun Os)"
		     break
		else
		       if [ $osch -eq 2 ] ; then
	        	     echo "You Pick up Linux (Red Hat)"
			     break
		       else
		             echo "What you don't like Unix/Linux OS."
			     break
		       fi
		fi
	else
		echo "Error: Please enter an integer."
	fi
done
